url: https://www.czechultimate.cz
baseurl: ""
title: ČAU Frisbee
description: Česká asociace ultimate frisbee
lang: cs_CZ
timezone: Europe/Prague
strict_front_matter: true

collections:
  authors:
    output: true

include: ['_pages']

paginate: 12
paginate_path: "/archiv/page:num/"

plugins:
   - jekyll-sitemap
   - jekyll-seo-tag
   - jekyll-paginate
   - jekyll-redirect-from

exclude:
- README.md
- Gemfile
- Gemfile.lock
- semantic.json
- package.json
- package-lock.json
- node_modules
- docker-compose.yml
- tutorial
- semantic/src
- semantic/tasks
- semantic/gulpfile.js
- semantic/semantic.json
- semantic/dist/semantic.js
- semantic/dist/semantic.css
